### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by denise-amiga** [Hezkore/deprecated-vscode-blitzmax-support#1]
the path can not have spaces

**Comment by Hezkore** [comment]
Fixed in commit  2fd212cd8372570525fae00d3ac836f2fa601a1e

**Comment by denise-amiga** [comment]
source file: 'Untitled 1.bmx'
error: Unable to open source file 'e:/tmp/Untitled.bmx'

**Comment by Hezkore** [comment]
Did you update the extension?
Or do you perhaps have a bad 'settings.json' pointing to the wrong '.bmx' file?
Try removing the '.vscode' folder.
Because I can't reproduce it on Windows.
I've got my 'Untitled 1.bmx' in 'd:/tmp/Untitled 1.bmx' and this is my result:
```
[ 97%] Processing:Untitled 1.bmx
[ 98%] Compiling:Untitled 1.bmx.console.debug.win32.x86.c
[100%] Linking:Untitled 1.exe
Executing:Untitled 1.exe
Hello World
```

**Comment by denise-amiga** [comment]
I've already seen where the fault is. Compiling with the blitzmaxng all ok, but with the blitzmax (legacy/1.50) is when it fails. Blitzmax (legacy/1.50) needs double quotes with names with spaces.

**Comment by Hezkore** [comment]
Are you sure?
My BMX Legacy version still compiles just fine... if I strip away some compile flags.
I've updated the extension to detect BMX NG and Legacy versions anyways.
And it'll automatically strip away flags like "-w" and "-quick" if the Legacy version is used.

**Comment by Hezkore** [comment]
As of version 1.4.7; 'PATH' is used for 'bcc' and 'bmk'.
I've tested this with both Legacy and NG BMX on Linux and Windows, and they all work with spaces in the BMX folder, project folder and filename.

So I'll just assume that this issue is no longer relevant.
