### ISSUE TITLE
Shows wrong tooltip text in other places when something is highlighted

### ISSUE THREAD

**Issue by woollybah** [Hezkore/deprecated-vscode-blitzmax-support#12]
**Setup (place X in matching boxes):**
 - [ x ] BlitzMax NG
 - [  ] BlitzMax Legacy
 - [ x ] Windows
 - [  ] Linux
 - [  ] MacOS

**Describe the bug**
When a keyword is highlighted in the editor, using ctrl-mouse-over to bring up info on something vscode doesn't understand shows the tooltip summary for the highlighted text.
This might be a bit confusing for some (like me!)

**Screenshots**
Note that `If` is the highlighted keyword at the beginning...
![wrong_tooltips](https://user-images.githubusercontent.com/95883/79759521-b062b700-8316-11ea-9978-0d29deacdfb4.gif)

**Comment by Hezkore** [comment]
Fixed in 01385b408320740ae5c1cb4207b7db34427ba49c.
