### ISSUE TITLE
Funky String auto-closing shenanigans

### ISSUE THREAD

**Issue by woollybah** [Hezkore/deprecated-vscode-blitzmax-support#14]
**Setup (place X in matching boxes):**
 - [ X ] BlitzMax NG
 - [  ] BlitzMax Legacy
 - [  ] Windows
 - [  ] Linux
 - [  ] MacOS

**Describe the bug**
When I attempt to type a sequence of three quotes ("), unfortunately it automagically adds a forth. 
Two pairs of quotes is not valid syntax anyway :-)

**Comment by Hezkore** [comment]
Version 1.30.0 now correctly closes quotes.
It correctly closes single and triple ones and follows the VSCode rules.
If you're still not satisfied with how brackets or quotes are closed you can change `editor.autoClosingQuotes` and `editor.autoClosingBrackets` in your standard VSCode settings.
