### ISSUE TITLE
Add a way to utilize the `-ud` option of `bmk`.

### ISSUE THREAD

**Issue by GalaxyCr8r** [Hezkore/deprecated-vscode-blitzmax-support#16]
**Describe the feature**
Currently there is no way for the user to define compiler options. `-ud` accepts a comma-separated list that will be made available to the code as compiler options in addition to the [defaults](https://blitzmax.org/docs/en/language/conditional_compiling/).

**Comment by GalaxyCr8r** [comment]
This is only really necessary because `'@bmk adddef ` apparently does nothing despite `bmk` suggesting its usage.

**Comment by Hezkore** [comment]
This is now supported in version 1.32.0.
Just add something like:
```
"conditionals": [
	"test",
	"console"
],
```
to your `tasks.json` file.

Remember that you're allowed to create multiple tasks inside your `tasks.json` file.
