### ISSUE TITLE
OUTLINE window is empty

### ISSUE THREAD

**Issue by VladDae** [Hezkore/deprecated-vscode-blitzmax-support#4]
**Setup (place X in matching boxes):**
 - [  ] BlitzMax NG
 - [ X ] BlitzMax Legacy
 - [ X ] Windows
 - [  ] Linux
 - [  ] MacOS

**Describe the bug**
Hi!
I'm wery apprisuate your extension. Love it! After about 15 years of old MaxIDE it is blessing)

Is it normal that my OUTLINES window is empty, while editing .bmx files? Maybe I miss some settings?

**Screenshots**
![Code_2020-01-08_10-20-25](https://user-images.githubusercontent.com/25726492/71958114-86bacf80-3200-11ea-88aa-6aa01d314dad.png)

**Comment by Hezkore** [comment]
Added symbol provider support in https://github.com/Hezkore/vscode-blitzmax-support/commit/5f5d2a59d8c5ef98e7a4ae69843e0542e04757d1
I've pushed the update to the VSCode Marketplace as version 1.17.0.
